### ISSUE TITLE
How do i lookup the ip?

### ISSUE THREAD

**Issue by n1ke33** [s0n1c268/IpLookUpBot#1]
What command do i use to lookup the ip?? 
i know the prefix is ? but what is the command

**Comment by s0n1c268** [comment]
You would use ?lookup IP address. This will only work with public IP addresses. Also, this is for educational purposes only.

**Comment by n1ke33** [comment]
thanks, how can i add embed to it.... and make it repeat only one time

**Comment by s0n1c268** [comment]
I don’t work with embeds. I do apologize. I will work on an embed bot in the near future. I’m also gonna close down this comments as well.
